### ISSUE TITLE
then what is difference between  tsml-py and sktime

### ISSUE THREAD

**Issue by Sandy4321** [time-series-machine-learning/tsml-py#14]
it is written on

https://github.com/time-series-machine-learning/tsml-java
UEA Time Series Classification
https://travis-ci.com/uea-machine-learning/tsml.svg?branch=master
A [Weka](https://svn.cms.waikato.ac.nz/svn/weka/branches/stable-3-8/)-compatible Java toolbox for time series classification, clustering and transformation. For the python sklearn-compatible version, see [sktime](https://github.com/alan-turing-institute/sktime)

but there is python repo
https://github.com/time-series-machine-learning/tsml-py

then what is difference between  tsml-py and sktime

**Comment by MatthewMiddlehurst** [comment]
Answered here https://github.com/time-series-machine-learning/tsml-java/issues/544
